[options.entry_points]
;invenio_base.api_apps =
;    invenio_userprofiles = invenio_userprofiles:InvenioUserProfiles
;invenio_base.api_finalize_app =
;    invenio_userprofiles = invenio_userprofiles.ext:api_finalize_app
;invenio_base.apps =
;    invenio_userprofiles = invenio_userprofiles:InvenioUserProfiles
;invenio_base.blueprints =
;    invenio_userprofiles = invenio_userprofiles.views:create_blueprint
invenio_base.finalize_app =
    invenio_notify = invenio_notify.ext:finalize_app
;invenio_db.alembic =
;    invenio_userprofiles = invenio_userprofiles:alembic
;invenio_i18n.translations =
;    messages = invenio_userprofiles

[build_sphinx]
source-dir = docs/
build-dir = docs/_build
all_files = 1