#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""create reviewer_map"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1742389623'
down_revision = '1740578602'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_map',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('reviewer_id', sa.Text(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'],
                                            name=op.f('fk_reviewer_map_user_id_accounts_user'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviewer_map'))
                    )
    op.create_index(op.f('ix_reviewer_map_user_id'), 'reviewer_map', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewer_map_user_id'), table_name='reviewer_map')
    op.drop_table('reviewer_map')
    # ### end Alembic commands ###
