#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""add noti_id field to endorsement_request table"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '1751030000'
down_revision = '1751019450'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endorsement_request', sa.Column('noti_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False))
    op.create_unique_constraint(op.f('uq_endorsement_request_noti_id'), 'endorsement_request', ['noti_id'])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_endorsement_request_noti_id'), 'endorsement_request', type_='unique')
    op.drop_column('endorsement_request', 'noti_id')
    # ### end Alembic commands ###