%% sources of file: invenio_notify/records/models.py

erDiagram
    User ||--o{ NotifyInboxModel : has
    User ||--o{ ReviewerMapModel : has
    User ||--o{ EndorsementRequestModel : creates
    
    ReviewerModel ||--o{ ReviewerMapModel : has
    ReviewerModel ||--o{ EndorsementModel : receives
    ReviewerModel ||--o{ EndorsementRequestModel : receives
    
    RDMRecordMetadata ||--o{ EndorsementModel : has
    RDMRecordMetadata ||--o{ EndorsementRequestModel : has
    
    NotifyInboxModel ||--|| EndorsementModel : references
    NotifyInboxModel ||--o{ EndorsementReplyModel : references
    
    EndorsementRequestModel ||--o{ EndorsementReplyModel : has
    EndorsementModel ||--o{ EndorsementReplyModel : references
    
    User {
        int id PK
        string email
        string name
        timestamp created
        timestamp updated
    }
    
    NotifyInboxModel {
        int id PK
        json raw
        text recid
        datetime process_date
        text process_note
        int user_id FK
        timestamp created
        timestamp updated
    }
    
    ReviewerMapModel {
        int id PK
        int user_id FK
        int reviewer_id FK
        timestamp created
        timestamp updated
    }
    
    ReviewerModel {
        int id PK
        text name
        text actor_id
        text inbox_url
        text inbox_api_token
        text description
        timestamp created
        timestamp updated
    }
    
    EndorsementModel {
        int id PK
        uuid record_id FK
        int reviewer_id FK
        text review_type
        int inbox_id FK
        text result_url
        text reviewer_name
        timestamp created
        timestamp updated
    }
    
    EndorsementRequestModel {
        int id PK
        uuid record_id FK
        int user_id FK
        int reviewer_id FK
        json raw
        text latest_status
        timestamp created
        timestamp updated
    }
    
    EndorsementReplyModel {
        int id PK
        int endorsement_request_id FK
        int inbox_id FK
        int endorsement_id FK
        text status
        text message
        timestamp created
        timestamp updated
    }
    
    RDMRecordMetadata {
        uuid id PK
        text title
    }
